### PR TITLE
Implement Universal Header

### PR DESCRIPTION
**Pull request by knitcodemonkey**

### CODE REVIEW

**Comment by beccalee123** [comment]
Seeing some buggy stuff on this one:
- All the font that should be white is showing up as a black
- The nav looks a little too small?
- No logo in the new subnav
- The main header seems to have lost a lot of formatting (and also that white font color issue again)
- The navigation on the side has disappeared/turned into outlines

I’ll attach some screenshots. 
screen shot 2018-05-03 at 3 21 51 pm
screen shot 2018-05-07 at 1 28 23 pm
screen shot 2018-05-07 at 1 27 22 pm
screen shot 2018-05-07 at 1 27 08 pm

**Comment by beccalee123** [comment]
This is looking much better! The header is still a little off, though. What I'm seeing:
- A few of the elements from the pink outline are showing up in weird places.
- The header looks like it scaled up on this new version (which could be ok, but we should re-center top-to-bottom if we go that route)
- The nav isn't centered top-to-bottom

Attaching screenshots of the PR build and the live version for reference!
pr screen shot 2018-05-07 at 4 44 24 pm
live screen shot 2018-05-07 at 4 44 35 pm

**Comment by knitcodemonkey** [comment]
I'll look into this tomorrow morning. Thank you, @beccalee123 !

**Comment by beccalee123** [comment]
Thanks for screensharing this morning! I approve!

**Pull request merged**
